# Generated by Django 3.1.6 on 2021-04-25 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vibe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vibe',
            field=models.ForeignKey(blank=True, db_column='vibe_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='vibe.vibe'),
        ),
    ]
